#!/bin/bash

backup="$HOME/.backup"
backup_loc="$HOME/Drive/Backup/dotfiles"

do_sort=true
do_backup=false

if [[ "$#" -lt 1 || "$1" == "--help" ]]; then
    echo "Usage: ${0##*/} [-g] [-n] [FILE]..."
    echo "  -g: Perform backup copying after adding"
    echo "  -n: Do not sort/uniq backup file after adding"
    [[ "$#" -lt 1 ]] && exit 1 || exit 0
fi

for file in "$@"; do
    case "$file" in
        "-n")
            do_sort=false
            ;;
        "-g")
            do_backup=true
            ;;
        *)
            fileloc=$(readlink -e "$file")
        echo $fileloc
        echo $fileloc >> "$backup"
    esac
done

if [[ do_sort ]]; then
    sort "$backup" -u -o "$backup"
fi

if [[ do_backup && -f "$backup" ]]; then
    backup_file=$(date +"%Y%m%d-%H%M%S.tar.gz")
    xargs --arg-file="$backup" tar -cvpzf "$backup_loc/$backup_file" "$backup"
fi
